### ISSUE TITLE
(omics.cli.run_analyzer) storageType is null for old runs.

### ISSUE THREAD

**Issue by hmkim** [awslabs/amazon-omics-tools#45]
In my case, the run has not the `storageType` of res variable.

> $ python -m omics.cli.run_analyzer 7379101 -o run_7379101.csv
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/Users/hyunmink/miniforge3/envs/boto3/lib/python3.12/site-packages/omics/cli/run_analyzer/__main__.py", line 489, in <module>
>     add_metrics(res, resources, pricing)
>   File "/Users/hyunmink/miniforge3/envs/boto3/lib/python3.12/site-packages/omics/cli/run_analyzer/__main__.py", line 339, in add_metrics
>     metrics["sizeReserved"] = f"{capacity} GiB"
>                                  ^^^^^^^^
> UnboundLocalError: cannot access local variable 'capacity' where it is not associated with a value

<img width="1189" alt="Screenshot 2024-08-05 at 12 34 05 PM" src="https://github.com/user-attachments/assets/eb1de062-1808-4c13-a9a4-a48bb8ed3e27">

**Comment by hmkim** [comment]
This appears to be an issue with runs that were probably run before HeathOmics announced support for the dynamic run storage type.

https://aws.amazon.com/about-aws/whats-new/2024/04/aws-healthomics-dynamic-run-storage-private-workflows/
